import type { Metadata } from "next";
import { TikTok_Sans } from "next/font/google";
import "./globals.css";
import { Auth0Provider } from "@auth0/nextjs-auth0";
import Header from "./components/Header";

const tikTokSans = TikTok_Sans({
  variable: "--font-tik-tok-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tikTokSans.variable} antialiased`}>
        <Auth0Provider>
          <Header />
          <main className="min-h-screen">{children}</main>
        </Auth0Provider>
      </body>
    </html>
  );
}
